# Maintain SSH through separate container and shared folder

apiVersion: v1
kind: Pod
metadata:
  name: client-app-with-ssh
  labels:
    app: client-app-with-ssh
spec:
  shareProcessNamespace: true
  initContainers:
  - name: fix-shared-perms
    image: busybox:1.36
    command:
    - sh
    - -lc
    - >
      mkdir -p /shared &&
      chown -R 1000:1000 /shared &&
      chmod -R u+rwX,g+rwX /shared
    volumeMounts:
    - name: shared
      mountPath: /shared
  containers:
  - name: app
    # REPLACE with the client's container image (e.g., ghcr.io/org/repo:tag)
    image: CONTAINER_IMAGE_URL
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: shared
      mountPath: /shared
  - name: ssh
    image: lscr.io/linuxserver/openssh-server:latest
    env:
    - name: PUID
      value: "1000"
    - name: PGID
      value: "1000"
    - name: TZ
      value: "UTC"
    - name: USER_NAME
      value: "ubuntu"
    - name: PUBLIC_KEY
      valueFrom:
        secretKeyRef:
          name: ssh-auth
          key: PUBLIC_KEY
    ports:
    - containerPort: 2222
    volumeMounts:
    - name: shared
      mountPath: /shared
  volumes:
  - name: shared
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: client-app-with-ssh-svc
spec:
  selector:
    app: client-app-with-ssh
  type: NodePort
  ports:
  - name: ssh
    protocol: TCP
    port: 2222
    targetPort: 2222
    nodePort: 30022
 

