apiVersion: v1
kind: Pod
metadata:
  name: client-app-direct-ssh
  labels:
    app: client-app-direct-ssh
spec:
  initContainers:
  - name: fix-perms
    image: busybox:1.36
    command:
    - sh
    - -lc
    - chown -R 1000:1000 /data && chmod 775 /data
    volumeMounts:
    - name: host-observable
      mountPath: /data
  containers:
  - name: app
    image: lscr.io/linuxserver/openssh-server:latest
    imagePullPolicy: IfNotPresent
    env:
    - name: PUBLIC_KEY
      valueFrom:
        secretKeyRef:
          name: ssh-authorized-keys
          key: authorized_keys
    - name: USER_NAME
      value: "ubuntu"
    - name: PUID
      value: "1000"
    - name: PGID
      value: "1000"
    ports:
    - containerPort: 2222
    volumeMounts:
    - name: host-observable
      mountPath: /data
  volumes:
  - name: host-observable
    hostPath:
      path: /var/lib/k8s/client-app-direct-ssh
      type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: client-app-direct-ssh-svc
spec:
  selector:
    app: client-app-direct-ssh
  type: NodePort
  ports:
  - name: ssh
    protocol: TCP
    port: 2222
    targetPort: 2222
    nodePort: 30022