apiVersion: v1
kind: Pod
metadata:
  name: client-app-direct-ssh
  labels:
    app: client-app-direct-ssh
spec:
  containers:
  - name: app
    image: ghcr.io/panubo/sshd:latest
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 22
    volumeMounts:
    - name: ssh-auth
      mountPath: /etc/authorized_keys/ubuntu
      subPath: authorized_keys
      readOnly: true
  volumes:
  - name: ssh-auth
    secret:
      secretName: ssh-authorized-keys
      items:
      - key: authorized_keys
        path: authorized_keys
      defaultMode: 0400
---
apiVersion: v1
kind: Service
metadata:
  name: client-app-direct-ssh-svc
spec:
  selector:
    app: client-app-direct-ssh
  type: NodePort
  ports:
  - name: ssh
    protocol: TCP
    port: 2222
    targetPort: 22
    nodePort: 30022