# HTTP echo pod that serves a static message

apiVersion: v1
kind: Pod
metadata:
  name: echo
  labels:
    app: echo
spec:
  containers:
  - name: echo
    image: hashicorp/http-echo
    args: ["-text=mock inference done"]
    ports:
    - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: echo-svc
spec:
  selector:
    app: echo
  type: NodePort
  ports:
  - port: 5678
    targetPort: 5678
    nodePort: 30080